#!/bin/sh

TODODIR="/usr/local/share/todo"

add_todo() {
    COUNT=0
    while [ -f "${TODODIR}/${COUNT}" ]
        do
            ((COUNT++))
        done
    vim "${TODODIR}/${COUNT}"
    RET=$?
    if [ $RET -eq "0" ]; then
        echo "New todo added. id: ${COUNT}"
    else echo "Addition failed. error code: ${RET}"
    fi
}

get_list() {
    if [ -s $TODODIR ]; then

        if [ "$1" != "donee" ]; then
            echo -e "\033[1mID\tContents\t\tDate\033[0m"
        fi

        for entry in $(ls -tr $TODODIR); do

            CONTENT="$(cat "${TODODIR}/${entry}")\t"
            if [ ${#CONTENT} -gt 16 ]; then
                CONTENT="${CONTENT::16}..."
            elif [ ${#CONTENT} -lt 8 ]; then
                CONTENT="$CONTENT\t"
            fi

            if [ $entry != "*" ]; then
                echo "$entry\t$CONTENT\t$(date -r "$TODODIR/$entry" "+%m-%d-%Y %H:%M:%S")"
            fi
        done
    else
        echo "Nothing to do."
    fi
}

complete_todo() {

    TARGET=$(get_list donee | fzf --reverse)
    INDEX=$(echo `expr "$TARGET" : '^\([0-9]*\)'`)

    if [ -f "$TODODIR/${INDEX}" ]; then
        rm "${TODODIR}/${INDEX}"
        RET=$?
        if [ $RET == "0" ]; then
            echo "Finished a todo."
        else
            echo "Deletion failed. error code: ${RET}"
        fi
    else echo "File not exists."
    fi
}

clear_repo() {
    rm -rf $TODODIR && mkdir $TODODIR
    echo "All todo is done."
}

COMMAND=$1
if [ ! -d "$TODODIR" ]; then
    mkdir $TODODIR
fi

case $COMMAND in
    add)
        add_todo ;;
    list)
        get_list ;;
    done)
        complete_todo ;;
    clear)
        clear_repo ;;
esac
